services:
  db:
    container_name: db_dev
    image: mysql:8.0.44
    env_file:
      - .env.dev
    volumes:
      - db_data_dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "${MYSQL_PORT}:3306"
    mem_limit: 512m
    cpus: 0.5 

networks:
  app-network:

volumes:
  db_data_dev:
