"""The migrations on MySQL, as every deployment's migrate service runs them.

Every other test builds its tables from the models (create_all), so without
these a migration that drifted from its model would only show up in E2E, or
in production.
"""
from pathlib import Path

import pytest
from alembic import command
from flask import current_app
from sqlalchemy import inspect

from app import db

MIGRATIONS = Path(__file__).resolve().parents[2] / 'migrations'


@pytest.fixture
def alembic_config(integration_app):
    """Alembic, pointed at an empty test database and emptied again after"""
    with integration_app.app_context():
        config = current_app.extensions['migrate'].migrate.get_config(str(MIGRATIONS))
        yield config
        command.downgrade(config, 'base')
        with db.engine.begin() as conn:
            conn.exec_driver_sql('DROP TABLE IF EXISTS alembic_version')


def _tables():
    return set(inspect(db.engine).get_table_names())


def test_migrations_build_the_schema_the_models_describe(alembic_config):
    command.upgrade(alembic_config, 'head')

    # Raises AutogenerateDiffsDetected naming every difference, such as a
    # column added to a model without a migration
    command.check(alembic_config)


def test_downgrade_removes_every_table(alembic_config):
    command.upgrade(alembic_config, 'head')
    assert {'users', 'notes'} <= _tables()

    command.downgrade(alembic_config, 'base')

    assert _tables() == {'alembic_version'}
